const exceptionToReviewMessage = {
    'PATH_NOT_CONTAIN_PACKAGE_JSON': 'kami tidak bisa menemukan file package.json pada submission yang kamu kirimkan, perlu diingat pada umumnya aplikasi node js memiliki file package.json untuk menyimpan konfigurasi project.',
    'PACKAGE_JSON_NOT_CONTAIN_SCRIPT_PROPERTY': 'file package.json yang kamu buat masih belum memiliki properti "script". Properti script ini digunakan sebagai shortcut untuk menjalankan command. Silakan sesuaikan isi script dengan kriteria submission ya',
    'RUNNER_SCRIPT_NOT_FOUND': 'sepertinya kamu lupa memasukkan command untuk menjalankan project ke dalam properti "script" pada file package.json. Silakan ditambahkan terlebih dahulu yaa.',
    'CANNOT_PARSE_PACKAGE_JSON': 'sepertinya file package.json yang kamu buat belum bisa terformat dengan baik. Silakan diperbaiki yaa.',
    'ESLINT_NOT_INSTALLED': 'Aplikasi yang kamu buat sudah berjalan dengan baik. Tetapi kode yang dituliskan masih ada yang bisa ditingkatkan. Sebaiknya gunakan salah satu style guide yang ada pada eslint agar kode yang kamu buat bisa semakin konsisten. Tingkatkan aplikasinya untuk latihan yaa. Semangattt!!',
    'ESLINT_ERROR' : 'Masih terdapat error ketika eslint dijalankan dengan perintah npx eslint ./src. Sebaiknya diperbaiki yaa, pastikan tidak ada warning atau error pada kode yang kamu buat.',
    'SEVER_FAILED_TO_START': '',
    'PORT_NOT_MEET_REQUIREMENT': 'port yang kamu gunakan untuk menjalankan aplikasi masih belum sesuai dengan kriteria submission, silakan dicek kembali kriterianya yaa.',
    'COMMAND_NOT_FOUND': 'command yang kamu masukkan tidak ditemukan, pastikan kamu sudah menginstallnya atau pastikan command yang kamu masukkan sudah benar dan tidak terjadi typo.',
    'MODULE_NOT_FOUND': 'sepertinya ada file yang tidak terimport dengan baik, pastikan path yang kamu gunakan sudah benar atau pastikan tidak ada typo pada path yang kamu masukkan.',
    'FAIL_INSTALLING_PACKAGE': 'package pada aplikasi yang kamu buat belum bisa di-install dengan baik.',
    'PROJECT_CONTAIN_DATABASE_DEPENDENCY': 'file package.json yang kamu buat memiliki dependency database yang tidak diperbolehkan. Perlu diingat bahwa untuk mengerjakan submission ini kamu tidak dipebolehkan menggunakan database seperti Postgres, MSSQL, MySQL, MariaDB, atau MongooDB untuk menyimpan data. Silakan <b>hapus dependency<b> tersebut dari file package.json ya.',
    'PROJECT_CONTAIN_OTHER_FRAMEWORK_DEPENDENCY': 'file package.json yang kamu buat memiliki dependency Framework lain yang tidak diperbolehkan. Perlu diingat bahwa untuk mengerjakan submission ini kamu tidak dipebolehkan menggunakan Framework lain selain Hapi Framework. Silakan <b>hapus dependency<b> tersebut dari file package.json ya.',
    'PROJECT_CONTAIN_NODE_MODULES' : 'project yang kamu buat memiliki folder <strong>node_modules</strong>. Perlu diingat bahwa <strong>node_modules</strong> tidak perlu dikirimkan ke dalam submission, <strong>node_modules</strong> akan didapatkan dengan cara menajalankan perintah install pada project. Silakan hapus terlebih dahulu folder <strong>node_modules</strong> seperti ketentuan submission.<img src="https://dicoding-web-img.sgp1.cdn.digitaloceanspaces.com/original/academy/dos:3fcde7eec6afcdee10efb449bd0f6dca20230215121207.png" style="width: 756px;" class="fr-fic fr-dib fr-draggable" data-success="true">',
    'RUNNER_COMMAND_CONTAIN_NODEMON' : 'kamu menggunakan nodemon pada start script. Pada submission ini kamu tidak diperbolehkan menggunakan nodemon sebagai start script utama, jika kamu ingin menggunakan nodemon silakan simpan di dalam start script lain, contohnya<pre>{<br>&nbsp;&nbsp;&nbsp;&nbsp;"name": "submission",<br>&nbsp;&nbsp;&nbsp;&nbsp;...<br>&nbsp;&nbsp;&nbsp;&nbsp;"scripts": {<br>&nbsp;&nbsp;&nbsp;&nbsp;"start": "node src/server.js",<br><strong>&nbsp; &nbsp; &nbsp; &nbsp; "start-dev": "nodemon src/server.js",</strong><br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>}</pre><br><img src="https://dicoding-web-img.sgp1.cdn.digitaloceanspaces.com/original/academy/dos:8d32e710e75d96597c17482ead576b4d20230215121505.png" style="width: 732px;" class="fr-fic fr-dib fr-draggable" data-success="true">'
}

export default exceptionToReviewMessage
